# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CFSS(object):
    def setupUi(self, CFSS):
        CFSS.setObjectName("CFSS")
        CFSS.resize(1154, 682)
        CFSS.setStyleSheet("/*https://www.realtimecolors.com/?colors=f2e7ef-1d0a18-e582ca-a30f7c-ff06bc&fonts=Inter-Inter*/")
        self.titlebar = QtWidgets.QFrame(CFSS)
        self.titlebar.setGeometry(QtCore.QRect(49, 0, 1101, 31))
        self.titlebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titlebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titlebar.setObjectName("titlebar")
        self.bg_2 = QtWidgets.QLabel(self.titlebar)
        self.bg_2.setGeometry(QtCore.QRect(0, 0, 1101, 31))
        self.bg_2.setStyleSheet("background-color:#1d0a18;\n"
"border-top-left-radius:19px;\n"
"border-top-right-radius:19px;\n"
"border-bottom:2px solid #e582ca;")
        self.bg_2.setText("")
        self.bg_2.setObjectName("bg_2")
        self.close = QtWidgets.QPushButton(self.titlebar)
        self.close.setGeometry(QtCore.QRect(1067, -4, 31, 31))
        self.close.setStyleSheet("font: 15pt \"Segoe UI Symbol\";\n"
"background-color:rgba(0,0,0,0);\n"
"color:#e582ca;\n"
"padding-top:2px;")
        self.close.setObjectName("close")
        self.mini_but = QtWidgets.QPushButton(self.titlebar)
        self.mini_but.setGeometry(QtCore.QRect(1040, 4, 31, 23))
        self.mini_but.setStyleSheet("font: 15pt \"Segoe UI Symbol\";\n"
"background-color:rgba(0,0,0,0);\n"
"color:#e582ca;\n"
"padding-bottom:5px;")
        self.mini_but.setObjectName("mini_but")
        self.window_title = QtWidgets.QLabel(self.titlebar)
        self.window_title.setGeometry(QtCore.QRect(40, 0, 351, 31))
        self.window_title.setStyleSheet("font: 13pt \"Hawkeye\";\n"
"color:white;")
        self.window_title.setObjectName("window_title")
        self.app_icon = QtWidgets.QLabel(self.titlebar)
        self.app_icon.setGeometry(QtCore.QRect(5, 0, 28, 28))
        self.app_icon.setText("")
        self.app_icon.setScaledContents(True)
        self.app_icon.setObjectName("app_icon")
        self.aksdjfkjladsfklsdf = QtWidgets.QPushButton(CFSS)
        self.aksdjfkjladsfklsdf.setGeometry(QtCore.QRect(-310, 190, 75, 23))
        self.aksdjfkjladsfklsdf.setObjectName("aksdjfkjladsfklsdf")
        self.sdfksdlkflksdfl = QtWidgets.QPushButton(CFSS)
        self.sdfksdlkflksdfl.setGeometry(QtCore.QRect(-230, 230, 75, 23))
        self.sdfksdlkflksdfl.setObjectName("sdfksdlkflksdfl")
        self.sidebar = QtWidgets.QFrame(CFSS)
        self.sidebar.setGeometry(QtCore.QRect(2, 285, 45, 91))
        self.sidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidebar.setObjectName("sidebar")
        self.bg_side_bar = QtWidgets.QLabel(self.sidebar)
        self.bg_side_bar.setGeometry(QtCore.QRect(0, 0, 45, 91))
        self.bg_side_bar.setStyleSheet("background-color:#1d0a18;\n"
"border-radius:10px;")
        self.bg_side_bar.setText("")
        self.bg_side_bar.setObjectName("bg_side_bar")
        self.paint_bucket_label = QtWidgets.QLabel(self.sidebar)
        self.paint_bucket_label.setGeometry(QtCore.QRect(3, 2, 39, 39))
        self.paint_bucket_label.setStyleSheet("background-color: rgb(0, 46, 255);")
        self.paint_bucket_label.setText("")
        self.paint_bucket_label.setScaledContents(True)
        self.paint_bucket_label.setObjectName("paint_bucket_label")
        self.paint_bucket = QtWidgets.QPushButton(self.sidebar)
        self.paint_bucket.setGeometry(QtCore.QRect(0, 0, 45, 45))
        self.paint_bucket.setObjectName("paint_bucket")
        self.converter_label = QtWidgets.QLabel(self.sidebar)
        self.converter_label.setGeometry(QtCore.QRect(3, 47, 39, 39))
        self.converter_label.setStyleSheet("background-color: rgb(0, 46, 255);")
        self.converter_label.setText("")
        self.converter_label.setScaledContents(True)
        self.converter_label.setObjectName("converter_label")
        self.coverter = QtWidgets.QPushButton(self.sidebar)
        self.coverter.setGeometry(QtCore.QRect(0, 45, 45, 45))
        self.coverter.setObjectName("coverter")
        self.container_frame = QtWidgets.QFrame(CFSS)
        self.container_frame.setGeometry(QtCore.QRect(50, 29, 1101, 651))
        self.container_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container_frame.setObjectName("container_frame")
        self.paint_editor_tab = QtWidgets.QFrame(self.container_frame)
        self.paint_editor_tab.setGeometry(QtCore.QRect(0, 0, 1101, 651))
        self.paint_editor_tab.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background:rgb(229, 130, 202);\n"
"    width: 15px;\n"
"    margin: 16px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background:rgb(229, 130, 202);\n"
"    border-radius:6px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    background: #000000;\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    background: #000000;\n"
"    height: 0px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover,\n"
"QScrollBar::sub-line:vertical:hover {\n"
"    background: #555555;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #333333;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: rgba(0,0,0,0);\n"
"}\n"
"")
        self.paint_editor_tab.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.paint_editor_tab.setFrameShadow(QtWidgets.QFrame.Raised)
        self.paint_editor_tab.setObjectName("paint_editor_tab")
        self.images_bg_textures = QtWidgets.QLabel(self.paint_editor_tab)
        self.images_bg_textures.setGeometry(QtCore.QRect(800, 10, 291, 101))
        self.images_bg_textures.setStyleSheet("background-color: rgb(39, 13, 32);\n"
"border-radius:10px;\n"
"border:2px solid rgb(229, 130, 202);\n"
"font: 15pt \"Hawkeye\";\n"
"color:white;")
        self.images_bg_textures.setAlignment(QtCore.Qt.AlignCenter)
        self.images_bg_textures.setObjectName("images_bg_textures")
        self.scrollArea = QtWidgets.QScrollArea(self.paint_editor_tab)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 771, 631))
        self.scrollArea.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scroll_images_area = QtWidgets.QWidget()
        self.scroll_images_area.setGeometry(QtCore.QRect(0, 0, 771, 631))
        self.scroll_images_area.setMinimumSize(QtCore.QSize(0, 0))
        self.scroll_images_area.setObjectName("scroll_images_area")
        self.scrollArea.setWidget(self.scroll_images_area)
        self.ConvertImages = QtWidgets.QPushButton(self.paint_editor_tab)
        self.ConvertImages.setGeometry(QtCore.QRect(888, 579, 201, 61))
        self.ConvertImages.setStyleSheet(".QPushButton{\n"
"background-color: rgb(39, 13, 32);\n"
"border-radius:10px;\n"
"border:2px solid rgb(229, 130, 202);\n"
"font: 15pt \"Hawkeye\";\n"
"color:white;\n"
"}\n"
"\n"
".QPushButton::pressed{\n"
"background-color: rgb(58, 19, 47);\n"
"}")
        self.ConvertImages.setObjectName("ConvertImages")
        self.bg = QtWidgets.QLabel(CFSS)
        self.bg.setGeometry(QtCore.QRect(49, 30, 1101, 651))
        self.bg.setStyleSheet("background-color:#1d0a18;\n"
"border-bottom-left-radius:19px;\n"
"border-bottom-right-radius:19px;")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.bg.raise_()
        self.aksdjfkjladsfklsdf.raise_()
        self.sdfksdlkflksdfl.raise_()
        self.sidebar.raise_()
        self.container_frame.raise_()
        self.titlebar.raise_()

        self.retranslateUi(CFSS)
        QtCore.QMetaObject.connectSlotsByName(CFSS)

    def retranslateUi(self, CFSS):
        _translate = QtCore.QCoreApplication.translate
        CFSS.setWindowTitle(_translate("CFSS", "FP"))
        self.close.setText(_translate("CFSS", "x"))
        self.mini_but.setText(_translate("CFSS", "-"))
        self.window_title.setText(_translate("CFSS", "Franks Painting"))
        self.aksdjfkjladsfklsdf.setText(_translate("CFSS", "PushButton"))
        self.aksdjfkjladsfklsdf.setShortcut(_translate("CFSS", "Left"))
        self.sdfksdlkflksdfl.setText(_translate("CFSS", "PushButton"))
        self.sdfksdlkflksdfl.setShortcut(_translate("CFSS", "Right"))
        self.paint_bucket.setText(_translate("CFSS", "paint bucket"))
        self.coverter.setText(_translate("CFSS", "converter"))
        self.images_bg_textures.setText(_translate("CFSS", "drag here"))
        self.ConvertImages.setText(_translate("CFSS", "Convert Images"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CFSS = QtWidgets.QWidget()
    ui = Ui_CFSS()
    ui.setupUi(CFSS)
    CFSS.show()
    sys.exit(app.exec_())
