# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(384, 208)
        self.message = QtWidgets.QLabel(Form)
        self.message.setGeometry(QtCore.QRect(0, 31, 384, 176))
        self.message.setStyleSheet("background-color:#0f070d;\n"
"border-bottom-left-radius:19px;\n"
"border-bottom-right-radius:19px;\n"
"font: 12pt \"CCLetterhackSansW03-Bold\";\n"
"color:white;\n"
"padding:30px;\n"
"padding-bottom:70px;")
        self.message.setAlignment(QtCore.Qt.AlignCenter)
        self.message.setWordWrap(True)
        self.message.setObjectName("message")
        self.titlebar = QtWidgets.QFrame(Form)
        self.titlebar.setGeometry(QtCore.QRect(0, 0, 1101, 31))
        self.titlebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titlebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titlebar.setObjectName("titlebar")
        self.bg_2 = QtWidgets.QLabel(self.titlebar)
        self.bg_2.setGeometry(QtCore.QRect(0, 0, 384, 31))
        self.bg_2.setStyleSheet("background-color:#0f070d;\n"
"border-top-left-radius:19px;\n"
"border-top-right-radius:19px;\n"
"border-bottom:2px solid #e582ca;")
        self.bg_2.setText("")
        self.bg_2.setObjectName("bg_2")
        self.close_but = QtWidgets.QPushButton(self.titlebar)
        self.close_but.setGeometry(QtCore.QRect(353, -4, 31, 31))
        self.close_but.setStyleSheet("font: 15pt \"Segoe UI Symbol\";\n"
"background-color:rgba(0,0,0,0);\n"
"color:#e582ca;\n"
"padding-top:2px;")
        self.close_but.setObjectName("close_but")
        self.mini_but = QtWidgets.QPushButton(self.titlebar)
        self.mini_but.setGeometry(QtCore.QRect(325, -70, 31, 23))
        self.mini_but.setStyleSheet("font: 15pt \"Segoe UI Symbol\";\n"
"background-color:rgba(0,0,0,0);\n"
"color:#e582ca;")
        self.mini_but.setObjectName("mini_but")
        self.window_title = QtWidgets.QLabel(self.titlebar)
        self.window_title.setGeometry(QtCore.QRect(10, 0, 201, 31))
        self.window_title.setStyleSheet("font: 13pt \"Hawkeye\";\n"
"color:white;")
        self.window_title.setObjectName("window_title")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 171, 231, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okbutton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.okbutton.setStyleSheet(".QPushButton{\n"
"font: 75 12pt \"CCLetterhackSansW03-Bold\";\n"
"background-color:#e582ca;\n"
"color:#49253f;\n"
"border-radius:6px;\n"
"height:30px;\n"
"}\n"
"\n"
".QPushButton::pressed{\n"
"background-color:#ff90c3;\n"
"}")
        self.okbutton.setObjectName("okbutton")
        self.horizontalLayout.addWidget(self.okbutton)
        self.open_log = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.open_log.setStyleSheet(".QPushButton{\n"
"font: 75 12pt \"CCLetterhackSansW03-Bold\";\n"
"background-color:#450b36;\n"
"color:#FFF;\n"
"border-radius:6px;\n"
"height:30px;\n"
"}\n"
"\n"
".QPushButton::pressed{\n"
"background-color:#ff90c3;\n"
"}")
        self.open_log.setObjectName("open_log")
        self.horizontalLayout.addWidget(self.open_log)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.message.setText(_translate("Form", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua"))
        self.close_but.setText(_translate("Form", "x"))
        self.mini_but.setText(_translate("Form", ""))
        self.window_title.setText(_translate("Form", "Coach frank Skate Shop"))
        self.okbutton.setText(_translate("Form", "Ok"))
        self.open_log.setText(_translate("Form", "Open log"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
