# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'template.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(759, 136)
        self.item_frame = QtWidgets.QFrame(Form)
        self.item_frame.setGeometry(QtCore.QRect(0, 0, 751, 131))
        self.item_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.item_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.item_frame.setObjectName("item_frame")
        self.main_item_bg = QtWidgets.QLabel(self.item_frame)
        self.main_item_bg.setGeometry(QtCore.QRect(26, 14, 691, 101))
        self.main_item_bg.setStyleSheet("background-color: rgb(52, 18, 43);\n"
"border-radius:10px;")
        self.main_item_bg.setText("")
        self.main_item_bg.setObjectName("main_item_bg")
        self.main_item_bg_shadow = QtWidgets.QLabel(self.item_frame)
        self.main_item_bg_shadow.setGeometry(QtCore.QRect(33, 21, 691, 101))
        self.main_item_bg_shadow.setStyleSheet("background-color: rgba(0, 0, 0, 250);\n"
"border-radius:10px;")
        self.main_item_bg_shadow.setText("")
        self.main_item_bg_shadow.setObjectName("main_item_bg_shadow")
        self.image_text = QtWidgets.QLabel(self.item_frame)
        self.image_text.setGeometry(QtCore.QRect(30, 18, 93, 93))
        self.image_text.setStyleSheet("background-color: rgb(255, 0, 4);\n"
"border-radius:6px;")
        self.image_text.setText("")
        self.image_text.setScaledContents(True)
        self.image_text.setObjectName("image_text")
        self.image_title = QtWidgets.QLabel(self.item_frame)
        self.image_title.setGeometry(QtCore.QRect(140, 24, 191, 31))
        self.image_title.setStyleSheet("font: 15pt \"Hawkeye\";\n"
"color:white;")
        self.image_title.setObjectName("image_title")
        self.opacity_slider = QtWidgets.QSlider(self.item_frame)
        self.opacity_slider.setGeometry(QtCore.QRect(569, 52, 141, 22))
        self.opacity_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 15px;\n"
"    margin: 0px;\n"
"    background-color: rgba(84, 193, 255, 0);\n"
"    border: 3px solid rgb(229, 130, 202);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color:rgb(229, 130, 202);\n"
"    height: 10px;\n"
"    width: 23px;\n"
"    margin: 2px;\n"
"    border-radius:5px;\n"
"}")
        self.opacity_slider.setProperty("value", 10)
        self.opacity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.opacity_slider.setObjectName("opacity_slider")
        self.opacity_title = QtWidgets.QLabel(self.item_frame)
        self.opacity_title.setGeometry(QtCore.QRect(570, 33, 111, 21))
        self.opacity_title.setStyleSheet("font: 10pt \"Hawkeye\";\n"
"color:rgb(117, 40, 98);")
        self.opacity_title.setObjectName("opacity_title")
        self.opacity_val = QtWidgets.QLabel(self.item_frame)
        self.opacity_val.setGeometry(QtCore.QRect(569, 76, 141, 21))
        self.opacity_val.setStyleSheet("font: 15pt \"Hawkeye\";\n"
"color:rgb(200, 114, 177);")
        self.opacity_val.setAlignment(QtCore.Qt.AlignCenter)
        self.opacity_val.setObjectName("opacity_val")
        self.close_page = QtWidgets.QPushButton(self.item_frame)
        self.close_page.setGeometry(QtCore.QRect(688, 10, 30, 31))
        self.close_page.setStyleSheet("font: 87 14pt \"Arial Black\";\n"
"background-color: rgba(255, 0, 4, 0);\n"
"border-radius:10px;\n"
"color:rgb(229, 130, 202);")
        self.close_page.setObjectName("close_page")
        self.alias_input = QtWidgets.QLineEdit(self.item_frame)
        self.alias_input.setGeometry(QtCore.QRect(140, 75, 221, 30))
        self.alias_input.setStyleSheet("border-radius:6px;\n"
"background-color: rgb(109, 37, 91);\n"
"border-bottom:1px solid rgb(229, 130, 202);\n"
"font: 10pt \"Hawkeye\";\n"
"color:rgb(200, 114, 177);")
        self.alias_input.setObjectName("alias_input")
        self.Alias_title = QtWidgets.QLabel(self.item_frame)
        self.Alias_title.setGeometry(QtCore.QRect(147, 55, 111, 20))
        self.Alias_title.setStyleSheet("font: 10pt \"Hawkeye\";\n"
"color:rgb(117, 40, 98);")
        self.Alias_title.setObjectName("Alias_title")
        self.out_res_label = QtWidgets.QLabel(self.item_frame)
        self.out_res_label.setGeometry(QtCore.QRect(400, 30, 111, 20))
        self.out_res_label.setStyleSheet("font: 10pt \"Hawkeye\";\n"
"color:rgb(117, 40, 98);")
        self.out_res_label.setAlignment(QtCore.Qt.AlignCenter)
        self.out_res_label.setObjectName("out_res_label")
        self.out_put_res_display = QtWidgets.QLabel(self.item_frame)
        self.out_put_res_display.setGeometry(QtCore.QRect(417, 47, 81, 31))
        self.out_put_res_display.setStyleSheet("font: 20pt \"Hawkeye\";\n"
"color:rgb(200, 114, 177);")
        self.out_put_res_display.setAlignment(QtCore.Qt.AlignCenter)
        self.out_put_res_display.setObjectName("out_put_res_display")
        self.up_res = QtWidgets.QPushButton(self.item_frame)
        self.up_res.setGeometry(QtCore.QRect(420, 80, 31, 23))
        self.up_res.setStyleSheet(".QPushButton{\n"
"background-color: rgb(72, 28, 71);\n"
"border-radius:4px;\n"
"font: 14pt \"Hawkeye\";\n"
"color:rgb(200, 114, 177);\n"
"}\n"
"\n"
".QPushButton::pressed{\n"
"background-color: rgb(58, 19, 47);\n"
"}")
        self.up_res.setText("")
        self.up_res.setObjectName("up_res")
        self.down_res = QtWidgets.QPushButton(self.item_frame)
        self.down_res.setGeometry(QtCore.QRect(463, 80, 31, 23))
        self.down_res.setStyleSheet(".QPushButton{\n"
"background-color: rgb(72, 28, 71);\n"
"border-radius:4px;\n"
"font: 14pt \"Hawkeye\";\n"
"color:rgb(200, 114, 177);\n"
"}\n"
"\n"
".QPushButton::pressed{\n"
"background-color: rgb(58, 19, 47);\n"
"}")
        self.down_res.setText("")
        self.down_res.setObjectName("down_res")
        self.main_item_bg_shadow.raise_()
        self.main_item_bg.raise_()
        self.image_text.raise_()
        self.image_title.raise_()
        self.opacity_slider.raise_()
        self.opacity_title.raise_()
        self.opacity_val.raise_()
        self.close_page.raise_()
        self.alias_input.raise_()
        self.Alias_title.raise_()
        self.out_res_label.raise_()
        self.out_put_res_display.raise_()
        self.up_res.raise_()
        self.down_res.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.image_title.setText(_translate("Form", "sample"))
        self.opacity_title.setText(_translate("Form", "opacity"))
        self.opacity_val.setText(_translate("Form", "10%"))
        self.close_page.setText(_translate("Form", "x"))
        self.alias_input.setText(_translate("Form", "0x0000000000000000"))
        self.Alias_title.setText(_translate("Form", "Alias"))
        self.out_res_label.setText(_translate("Form", "Output res"))
        self.out_put_res_display.setText(_translate("Form", "512"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
